### ISSUE TITLE
No file shows in Design Hierarchy after new project

### ISSUE THREAD

**Issue by alain-rs** [os-fpga/FOEDAG#221] opened 2022-03-04 17:20 UTC
I create a new project, add one .v file finish the project, no file shows in the design hierarchy.

**Comment by liibin** [comment] 2022-03-08 01:34
I found that this problem occurs if I create an existing project name.

**Comment by KochynVolodymyr** [comment] 2022-06-21 08:53
Can't reproduce with this steps. All works fine.

**Comment by ravic-rs** [comment] 2022-09-01 03:31
Closing as complete.

**Closed by ravic-rs** 2022-09-01 03:31 UTC
